In [1]:
import pandas as pd
import numpy as np

In [2]:
data_preprocessed = pd.read_csv('Absenteeism_preprocessed.csv')

In [3]:
data_preprocessed.head()

,reason1,reason2,reason3,reason4,Month Value,Day of Week,Transportation Expense,Distance to Work,Age,Daily Work Load Average,Body Mass Index,Education,Children,Pets,Absenteeism Time in Hours
0,0,0,0,1,7,1,289,36,33,239.554,30,0,2,1,4
1,0,0,0,0,7,1,118,13,50,239.554,31,0,1,0,0
2,0,0,0,1,7,2,179,51,38,239.554,31,0,0,0,2
3,1,0,0,0,7,3,279,5,39,239.554,24,0,2,0,4
4,0,0,0,1,7,3,289,36,33,239.554,30,0,2,1,2

In [4]:
data_preprocessed['Absenteeism Time in Hours'].median()

3.0

In [5]:
targets = np.where(data_preprocessed['Absenteeism Time in Hours'] >
                   data_preprocessed['Absenteeism Time in Hours'].median(), 1, 0)
targets

array([1, 0, 0, 1, 0, 0, 1, 1, 1, 1, 1, 1, 1, 0, 1, 1, 0, 1, 1, 0, 1, 0,
       1, 1, 1, 1, 0, 1, 1, 0, 1, 1, 1, 1, 0, 0, 1, 1, 1, 1, 0, 1, 1, 1,
       0, 0, 0, 1, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 1, 1, 0, 1, 1, 0, 1, 0, 0, 0, 0, 1, 1, 1, 1, 1, 1,
       0, 1, 0, 1, 0, 1, 0, 0, 1, 0, 0, 1, 0, 1, 0, 1, 1, 1, 0, 0, 0, 1,
       0, 1, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 0,
       0, 0, 0, 0, 0, 0, 1, 1, 0, 1, 0, 1, 1, 1, 0, 0, 0, 1, 0, 1, 0, 0,
       1, 0, 1, 0, 1, 1, 1, 1, 0, 1, 1, 1, 1, 1, 1, 1, 1, 0, 1, 1, 0, 1,
       0, 1, 1, 0, 1, 0, 0, 0, 0, 0, 0, 1, 0, 0, 1, 1, 0, 0, 1, 0, 1, 1,
       1, 1, 1, 1, 0, 0, 1, 0, 0, 1, 1, 1, 0, 0, 1, 0, 0, 0, 0, 0, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0, 1, 1, 0, 0, 0, 1, 1, 1, 1, 1, 1,
       0, 1, 1, 0, 1, 1, 1, 1, 1, 0, 1, 0, 0, 1, 0, 0, 1, 1, 0, 1, 0, 0,
       0, 0, 0, 1, 1, 1, 1, 0, 1, 0, 1, 0, 0, 0, 1, 1, 0, 1, 1, 1, 0, 0,
       0, 1, 1, 1, 1, 1, 1, 0, 0, 1, 0, 1, 0, 1, 0, 1, 0, 0, 0, 0, 0, 1,
       1, 0, 1, 0, 0, 0, 1, 1, 0, 1, 0, 1, 0, 0, 1, 1, 1, 0, 0, 0, 0, 0,
       1, 1, 1, 0, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 0, 0, 0, 1, 0, 0,
       1, 1, 1, 0, 0, 1, 1, 1, 0, 0, 1, 1, 1, 1, 1, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 1, 1, 0, 1, 0, 0, 0, 1, 0, 0, 1, 0, 0, 1, 1, 0, 1, 0, 1,
       1, 1, 1, 1, 0, 1, 0, 0, 1, 0, 0, 0, 1, 1, 1, 0, 1, 0, 1, 1, 1, 1,
       1, 0, 1, 1, 1, 1, 0, 1, 0, 1, 0, 1, 0, 0, 0, 0, 1, 0, 1, 0, 0, 1,
       0, 0, 0, 0, 1, 1, 0, 1, 1, 0, 1, 1, 0, 0, 0, 1, 0, 0, 0, 1, 0, 1,
       1, 1, 1, 1, 1, 1, 1, 0, 0, 1, 0, 0, 1, 1, 1, 0, 0, 0, 1, 0, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 0, 1, 0, 0, 0, 0, 0, 0, 0, 1, 0, 1, 0, 0, 1,
       1, 0, 0, 1, 0, 0, 0, 0, 0, 0, 1, 0, 1, 1, 0, 0, 0, 1, 0, 1, 0, 1,
       1, 1, 0, 0, 0, 0, 1, 0, 1, 1, 1, 1, 1, 0, 0, 0, 0, 1, 1, 0, 0, 0,
       1, 0, 0, 1, 0, 1, 0, 0, 0, 0, 0, 1, 0, 1, 1, 1, 0, 0, 0, 1, 1, 1,
       0, 0, 0, 0, 1, 0, 0, 1, 0, 0, 1, 0, 0, 1, 0, 1, 0, 0, 0, 0, 0, 0,
       0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 1, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 1, 1, 0, 0, 0, 1, 0, 0, 1,
       0, 1, 0, 0, 0, 0, 0, 0, 0, 1, 1, 0, 0, 0, 1, 1, 1, 1, 1, 1, 1, 0,
       1, 0, 0, 0, 0, 1, 0, 1, 0, 0, 1, 1, 0, 0, 1, 0, 0, 0, 1, 0, 0, 1,
       1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 1, 1, 0, 1, 0, 0])

In [6]:
data_preprocessed['Excessive Absenteeism'] = targets
data_preprocessed.head()

,reason1,reason2,reason3,reason4,Month Value,Day of Week,Transportation Expense,Distance to Work,Age,Daily Work Load Average,Body Mass Index,Education,Children,Pets,Absenteeism Time in Hours,Excessive Absenteeism
0,0,0,0,1,7,1,289,36,33,239.554,30,0,2,1,4,1
1,0,0,0,0,7,1,118,13,50,239.554,31,0,1,0,0,0
2,0,0,0,1,7,2,179,51,38,239.554,31,0,0,0,2,0
3,1,0,0,0,7,3,279,5,39,239.554,24,0,2,0,4,1
4,0,0,0,1,7,3,289,36,33,239.554,30,0,2,1,2,0

In [7]:
data_preprocessed['Excessive Absenteeism'].value_counts()

0    381
1    319
Name: Excessive Absenteeism, dtype: int64

In [8]:
targets.sum()/targets.shape[0]

0.45571428571428574

In [9]:
#data_targets = data_preprocessed.drop(['Absenteeism Time in Hours'],axis=1)
#data_targets.head()

#Backward Elimination (eliminate columns with insignificant weights)
data_targets = data_preprocessed.drop(['Absenteeism Time in Hours','Distance to Work','Daily Work Load Average',
                                      'Day of Week'],axis=1)
data_targets.head()

,reason1,reason2,reason3,reason4,Month Value,Transportation Expense,Age,Body Mass Index,Education,Children,Pets,Excessive Absenteeism
0,0,0,0,1,7,289,33,30,0,2,1,1
1,0,0,0,0,7,118,50,31,0,1,0,0
2,0,0,0,1,7,179,38,31,0,0,0,0
3,1,0,0,0,7,279,39,24,0,2,0,1
4,0,0,0,1,7,289,33,30,0,2,1,0

In [10]:
unscaled_data = data_targets.iloc[:,:-1]

In [11]:
from sklearn.preprocessing import StandardScaler

In [12]:
absenteeism_scaler = StandardScaler()

In [13]:
# import the libraries needed to create the Custom Scaler
# note that all of them are a part of the sklearn package
# moreover, one of them is actually the StandardScaler module, 
# so you can imagine that the Custom Scaler is build on it

from sklearn.base import BaseEstimator, TransformerMixin
from sklearn.preprocessing import StandardScaler

# create the Custom Scaler class

class CustomScaler(BaseEstimator,TransformerMixin): 
    
    # init or what information we need to declare a CustomScaler object
    # and what is calculated/declared as we do
    
    def __init__(self,columns,copy=True,with_mean=True,with_std=True):
        
        # scaler is nothing but a Standard Scaler object
        self.scaler = StandardScaler(copy,with_mean,with_std)
        # with some columns 'twist'
        self.columns = columns
        self.mean_ = None
        self.var_ = None
        
    
    # the fit method, which, again based on StandardScale
    
    def fit(self, X, y=None):
        self.scaler.fit(X[self.columns], y)
        self.mean_ = np.mean(X[self.columns])
        self.var_ = np.var(X[self.columns])
        return self
    
    # the transform method which does the actual scaling

    def transform(self, X, y=None, copy=None):
        
        # record the initial order of the columns
        init_col_order = X.columns
        
        # scale all features that you chose when creating the instance of the class
        X_scaled = pd.DataFrame(self.scaler.transform(X[self.columns]), columns=self.columns)
        
        # declare a variable containing all information that was not scaled
        X_not_scaled = X.loc[:,~X.columns.isin(self.columns)]
        
        # return a data frame which contains all scaled features and all 'not scaled' features
        # use the original order (that you recorded in the beginning)
        return pd.concat([X_not_scaled, X_scaled], axis=1)[init_col_order]

In [14]:
# check what are all columns that we've got
unscaled_data.columns.values

array(['reason1', 'reason2', 'reason3', 'reason4', 'Month Value',
       'Transportation Expense', 'Age', 'Body Mass Index', 'Education',
       'Children', 'Pets'], dtype=object)

In [15]:
# choose the columns to scale
# we later augmented this code and put it in comments
# columns_to_scale = ['Month Value','Day of the Week', 'Transportation Expense', 'Distance to Work',
       #'Age', 'Daily Work Load Average', 'Body Mass Index', 'Children', 'Pet']
    
# select the columns to omit
columns_to_omit = ['reason1', 'reason2', 'reason3', 'reason4','Education']

In [16]:
# create the columns to scale, based on the columns to omit
# use list comprehension to iterate over the list
columns_to_scale = [x for x in unscaled_data.columns.values if x not in columns_to_omit]
columns_to_scale

['Month Value',
 'Transportation Expense',
 'Age',
 'Body Mass Index',
 'Children',
 'Pets']

In [17]:
# declare a scaler object, specifying the columns you want to scale
absenteeism_scaler = CustomScaler(columns_to_scale)

In [18]:
absenteeism_scaler.fit(unscaled_data)

CustomScaler(columns=['Month Value', 'Transportation Expense', 'Age',
                      'Body Mass Index', 'Children', 'Pets'],
             copy=None, with_mean=None, with_std=None)

In [19]:
# standardizes the data, using the transform method 
# in the last line, we fitted the data - in other words
# we found the internal parameters of a model that will be used to transform data. 
# transforming applies these parameters to our data
# note that when you get new data, you can just call 'scaler' again and transform it in the same way as now
scaled_data = absenteeism_scaler.transform(unscaled_data)

In [20]:
scaled_data

,reason1,reason2,reason3,reason4,Month Value,Transportation Expense,Age,Body Mass Index,Education,Children,Pets
0,0,0,0,1,0.182726,1.005844,-0.536062,0.767431,0,0.880469,0.268487
1,0,0,0,0,0.182726,-1.574681,2.130803,1.002633,0,-0.019280,-0.589690
2,0,0,0,1,0.182726,-0.654143,0.248310,1.002633,0,-0.919030,-0.589690
3,1,0,0,0,0.182726,0.854936,0.405184,-0.643782,0,0.880469,-0.589690
4,0,0,0,1,0.182726,1.005844,-0.536062,0.767431,0,0.880469,0.268487
5,0,0,0,1,0.182726,-0.654143,0.248310,1.002633,0,-0.919030,-0.589690
6,0,0,0,1,0.182726,2.092381,-1.320435,0.061825,0,-0.019280,2.843016
7,0,0,0,1,0.182726,0.568211,-0.065439,-0.878984,0,2.679969,-0.589690
8,0,0,1,0,0.182726,-1.016322,-0.379188,-0.408580,0,0.880469,-0.589690
9,0,0,0,1,0.182726,0.190942,0.091435,0.532229,1,-0.019280,0.268487
10,1,0,0,0,0.182726,0.568211,-0.065439,-0.878984,0,2.679969,-0.589690
11,1,0,0,0,0.182726,0.568211,-0.065439,-0.878984,0,2.679969,-0.589690
12,1,0,0,0,0.182726,0.568211,-0.065439,-0.878984,0,2.679969,-0.589690
13,1,0,0,0,0.182726,-0.654143,0.248310,1.002633,0,-0.919030,-0.589690
14,0,0,0,1,0.182726,-0.654143,0.248310,1.002633,0,-0.919030,-0.589690
15,1,0,0,0,0.182726,0.356940,0.718933,-0.878984,0,-0.919030,-0.589690
16,0,0,0,1,0.182726,-0.654143,0.248310,1.002633,0,-0.919030,-0.589690
17,0,0,1,0,0.182726,-0.654143,0.248310,1.002633,0,-0.919030,-0.589690
18,1,0,0,0,0.182726,-0.503235,-0.536062,-0.408580,0,0.880469,1.126663
19,0,0,0,1,0.468236,0.387122,1.660180,1.237836,0,0.880469,0.268487
20,1,0,0,0,0.468236,1.624567,-1.320435,-0.408580,1,-0.919030,-0.589690
21,1,0,0,0,0.468236,-0.654143,0.248310,1.002633,0,-0.919030,-0.589690
22,1,0,0,0,0.468236,2.092381,-1.320435,0.061825,0,-0.019280,2.843016
23,0,0,0,1,0.468236,0.568211,-0.065439,-0.878984,0,2.679969,-0.589690
24,0,0,1,0,0.468236,1.005844,-0.536062,0.767431,0,0.880469,0.268487
25,0,0,0,1,0.468236,2.092381,-1.320435,0.061825,0,-0.019280,2.843016
26,0,0,0,1,0.468236,1.005844,-0.536062,0.767431,0,0.880469,0.268487
27,0,0,0,1,0.468236,-0.986140,-1.163560,-1.114186,0,-0.919030,-0.589690
28,0,0,1,0,0.468236,1.005844,-0.536062,0.767431,0,0.880469,0.268487
29,0,0,0,1,0.468236,-0.654143,0.248310,1.002633,0,-0.919030,-0.589690
...,...,...,...,...,...,...,...,...,...,...,...
670,0,0,0,1,-0.673803,-1.016322,-0.379188,-0.408580,0,0.880469,-0.589690
671,0,0,1,0,-0.673803,0.040034,-1.320435,-0.643782,0,-0.019280,1.126663
672,1,0,0,0,-0.673803,-1.574681,2.130803,1.002633,0,-0.019280,-0.589690
673,0,0,0,1,-0.673803,-0.654143,-1.006686,-1.819793,1,-0.919030,-0.589690
674,0,0,0,1,-0.388293,0.190942,0.091435,0.532229,1,-0.019280,0.268487
675,0,0,1,0,-0.388293,0.040034,0.718933,0.297027,1,0.880469,1.126663
676,0,0,0,1,-0.388293,0.190942,-0.692937,-0.408580,1,-0.919030,-0.589690
677,1,0,0,0,-0.388293,-1.574681,0.091435,0.297027,0,-0.919030,-0.589690
678,0,0,0,1,-0.388293,0.190942,1.032682,2.649049,0,-0.019280,-0.589690
679,1,0,0,0,-0.388293,-0.654143,-1.006686,-1.819793,1,-0.919030,-0.589690
680,0,0,0,1,-0.388293,1.036026,0.562059,-0.408580,0,-0.019280,0.268487
681,1,0,0,0,-0.388293,0.040034,0.718933,0.297027,1,0.880469,1.126663
682,0,0,1,0,-0.388293,1.171843,1.032682,-0.408580,0,0.880469,0.268487
683,0,0,0,1,-0.388293,0.040034,0.718933,0.297027,1,0.880469,1.126663
684,0,0,0,1,-0.388293,-0.654143,-1.006686,-1.819793,1,-0.919030,-0.589690
685,0,0,0,1,-0.388293,-1.574681,2.130803,1.002633,0,-0.019280,-0.589690
686,1,0,0,0,-0.388293,-1.574681,2.130803,1.002633,0,-0.019280,-0.589690
687,0,0,0,1,-0.388293,-1.574681,0.091435,0.297027,0,-0.919030,-0.589690
688,0,0,0,0,-0.388293,-1.574681,2.130803,1.002633,0,-0.019280,-0.589690
689,0,0,0,1,-0.388293,-0.654143,-1.006686,-1.819793,1,-0.919030,-0.589690
690,0,0,0,0,-0.388293,2.348925,-0.065439,-1.349389,0,0.880469,2.843016
691,0,1,0,0,-0.388293,-0.654143,0.562059,-1.114186,1,0.880469,-0.589690
692,1,0,0,0,-0.388293,-1.016322,-0.379188,-0.408580,0,0.880469,-0.589690
693,1,0,0,0,-0.388293,0.190942,-0.692937,-0.408580,1,-0.919030,-0.589690
694,0,0,0,1,-0.388293,1.036026,0.562059,-0.408580,0,-0.019280,0.268487
695,1,0,0,0,-0.388293,-0.654143,0.562059,-1.114186,1,0.880469,-0.589690
696,1,0,0,0,-0.388293,0.040034,-1.320435,-0.643782,0,-0.019280,1.126663
697,1,0,0,0,-0.388293,1.624567,-1.320435,-0.408580,1,-0.919030,-0.589690
698,0,0,0,1,-0.388293,0.190942,-0.692937,-0.408580,1,-0.919030,-0.589690
699,0,0,0,1,-0.388293,1.036026,0.562059,-0.408580,0,-0.019280,0.268487

In [21]:
from sklearn.model_selection import train_test_split

In [22]:
train_test_split(scaled_data, targets)

[     reason1  reason2  reason3  reason4  Month Value  Transportation Expense  \
 504        0        0        0        1     0.753746               -0.654143
 566        0        0        0        1     1.610276                0.040034
 304        0        0        0        1     1.039256                0.190942
 678        0        0        0        1    -0.388293                0.190942
 144        1        0        0        0    -1.244823                2.499833
 19         0        0        0        1     0.468236                0.387122
 495        0        0        0        1     0.753746                0.356940
 468        0        1        0        0     0.182726                1.171843
 675        0        0        1        0    -0.388293                0.040034
 249        0        0        1        0     0.182726                1.005844
 342        0        0        0        1     1.610276                0.190942
 664        1        0        0        0    -0.673803               -1.574681
 209        1        0        0        0    -0.388293               -0.578689
 434        0        0        1        0    -0.388293                0.085306
 43         0        0        1        0     0.753746                0.190942
 498        0        0        0        1     0.753746               -1.016322
 243        1        0        0        0     0.182726                1.624567
 168        1        0        0        0    -0.959313                1.005844
 232        0        0        0        1    -0.102784                2.348925
 630        1        0        0        0    -0.959313               -0.654143
 230        0        0        0        1    -0.102784               -1.574681
 154        0        0        1        0    -1.244823               -0.503235
 640        0        0        0        1    -0.959313                0.085306
 5          0        0        0        1     0.182726               -0.654143
 388        0        0        0        1    -1.244823               -0.654143
 489        0        0        0        1     0.468236                1.624567
 40         0        0        0        1     0.753746               -0.578689
 252        0        0        1        0     0.468236                1.005844
 586        0        0        0        1    -1.244823                0.040034
 683        0        0        0        1    -0.388293                0.040034
 ..       ...      ...      ...      ...          ...                     ...
 391        0        0        1        0    -0.959313                0.356940
 184        0        0        0        1    -0.673803                1.036026
 309        0        0        0        1     1.039256               -1.574681
 430        0        0        0        1    -0.388293                2.092381
 479        0        0        0        1     0.182726                0.854936
 493        0        0        0        1     0.468236                1.036026
 655        1        0        0        0    -0.673803               -1.574681
 49         1        0        0        0     0.753746                1.036026
 289        0        0        0        1     1.039256                1.005844
 583        0        0        0        1    -1.530333               -0.654143
 686        1        0        0        0    -0.388293               -1.574681
 64         0        0        0        0     1.039256               -1.574681
 357        0        0        1        0     1.610276                1.005844
 429        0        0        0        1    -0.388293               -0.654143
 469        0        0        0        1     0.182726                0.190942
 367        0        0        0        1    -1.530333               -0.654143
 538        1        0        0        0     1.324766                0.190942
 319        1        0        0        0     1.324766               -0.654143
 288        1        0        0        0     0.753746               -0.654143
 487        0        0        0        1     0.468236               -0.654143
 646        0        0        0        1    -0.959313               -0.654143
 187        1        0        0        0    -0.673803                0.356940
 619        0        0        0        1    -0.959313                0.387122
 542        1        0        0        0     1.324766               -1.574681
 146        0        0        0        1    -1.244823                0.040034
 150        0        0        0        1    -1.244823                0.040034
 615        0        0        0        1    -1.244823               -0.654143
 450        0        0        0        1    -0.102784               -0.654143
 516        0        0        0        1     1.039256                2.213108
 500        0        0        0        1     0.753746               -0.654143

           Age  Body Mass Index  Education  Children      Pets
 504 -1.006686        -1.819793          1 -0.919030 -0.589690
 566 -1.320435        -0.643782          0 -0.019280  1.126663
 304  1.032682         2.649049          0 -0.019280 -0.589690
 678  1.032682         2.649049          0 -0.019280 -0.589690
 144  2.130803        -0.643782          0 -0.919030 -0.589690
 19   1.660180         1.237836          0  0.880469  0.268487
 495  0.718933        -0.878984          0 -0.919030 -0.589690
 468  1.032682        -0.408580          0  0.880469  0.268487
 675  0.718933         0.297027          1  0.880469  1.126663
 249 -0.536062         0.767431          0  0.880469  0.268487
 342  0.091435         0.532229          1 -0.019280  0.268487
 664  0.091435         0.297027          0 -0.919030 -0.589690
 209 -1.477309        -1.349389          0 -0.919030 -0.589690
 434  3.385799        -1.114186          0  0.880469  0.268487
 43   1.032682         2.649049          0 -0.019280 -0.589690
 498 -0.379188        -0.408580          0  0.880469 -0.589690
 243 -1.320435        -0.408580          1 -0.919030 -0.589690
 168 -0.536062         0.767431          0  0.880469  0.268487
 232 -0.065439        -1.349389          0  0.880469  2.843016
 630  0.248310         1.002633          0 -0.919030 -0.589690
 230  2.130803         1.002633          0 -0.019280 -0.589690
 154 -0.536062        -0.408580          0  0.880469  1.126663
 640  3.385799        -1.114186          0  0.880469  0.268487
 5    0.248310         1.002633          0 -0.919030 -0.589690
 388  0.248310         1.002633          0 -0.919030 -0.589690
 489 -1.320435        -0.408580          1 -0.919030 -0.589690
 40  -1.477309        -1.349389          0 -0.919030 -0.589690
 252 -0.536062         0.767431          0  0.880469  0.268487
 586 -1.320435        -0.643782          0 -0.019280  1.126663
 683  0.718933         0.297027          1  0.880469  1.126663
 ..        ...              ...        ...       ...       ...
 391  0.718933        -0.878984          0 -0.919030 -0.589690
 184  0.562059        -0.408580          0 -0.019280  0.268487
 309  2.130803         1.002633          0 -0.019280 -0.589690
 430 -1.320435         0.061825          0 -0.019280  2.843016
 479  0.405184        -0.643782          0  0.880469 -0.589690
 493  0.562059        -0.408580          0 -0.019280  0.268487
 655  0.091435         0.297027          0 -0.919030 -0.589690
 49   0.562059        -0.408580          0 -0.019280  0.268487
 289 -0.536062         0.767431          0  0.880469  0.268487
 583  0.248310         1.002633          0 -0.919030 -0.589690
 686  2.130803         1.002633          0 -0.019280 -0.589690
 64   2.130803         1.002633          0 -0.019280 -0.589690
 357 -0.536062         0.767431          0  0.880469  0.268487
 429  0.248310         1.002633          0 -0.919030 -0.589690
 469  1.817054         1.473038          0 -0.019280  3.701192
 367  0.248310         1.002633          0 -0.919030 -0.589690
 538 -0.692937        -0.408580          1 -0.919030 -0.589690
 319  0.248310         1.002633          0 -0.919030 -0.589690
 288  0.248310         1.002633          0 -0.919030 -0.589690
 487  0.248310         1.002633          0 -0.919030 -0.589690
 646  0.248310         1.002633          0 -0.919030 -0.589690
 187  0.718933        -0.878984          0 -0.919030 -0.589690
 619  1.660180         1.237836          0  0.880469  0.268487
 542  0.091435         0.297027          0 -0.919030 -0.589690
 146 -1.320435        -0.643782          0 -0.019280  1.126663
 150 -1.320435        -0.643782          0 -0.019280  1.126663
 615  0.248310         1.002633          0 -0.919030 -0.589690
 450  0.248310         1.002633          0 -0.919030 -0.589690
 516 -0.849811        -0.408580          0  1.780219 -0.589690
 500 -1.006686        -1.819793          1 -0.919030 -0.589690

 [525 rows x 11 columns],
      reason1  reason2  reason3  reason4  Month Value  Transportation Expense  \
 427        1        0        0        0    -0.388293                2.213108
 695        1        0        0        0    -0.388293               -0.654143
 305        0        0        0        1     1.039256                0.190942
 510        1        0        0        0     1.039256                1.005844
 650        0        0        0        1    -0.959313               -0.654143
 613        0        0        0        1    -1.244823                0.387122
 439        1        0        0        0    -0.388293                0.190942
 454        0        0        0        1    -0.102784               -1.574681
 677        1        0        0        0    -0.388293               -1.574681
 141        0        0        0        1    -1.244823               -0.503235
 188        0        0        0        1    -0.673803               -1.016322
 172        1        0        0        0    -0.959313                0.854936
 136        0        0        0        1    -1.530333                1.005844
 176        1        0        0        0    -0.959313               -0.654143
 59         0        0        0        1     0.753746                0.387122
 318        0        0        0        1     1.324766                0.387122
 353        1        0        0        0     1.610276                0.190942
 311        0        0        0        0     1.039256                0.568211
 590        0        0        0        1    -1.244823               -0.654143
 114        0        0        1        0    -1.530333               -1.574681
 178        1        0        0        0    -0.959313                0.040034
 588        0        0        0        1    -1.244823               -0.654143
 548        0        0        0        0     1.324766                1.036026
 167        1        0        0        0    -0.959313               -1.016322
 290        0        0        0        1     1.039256                0.190942
 552        0        0        0        1     1.324766                0.040034
 670        0        0        0        1    -0.673803               -1.016322
 102        0        0        0        1     1.610276                0.040034
 446        0        0        0        0    -0.102784               -0.654143
 451        0        0        0        1    -0.102784                0.190942
 ..       ...      ...      ...      ...          ...                     ...
 457        0        0        0        1    -0.102784                0.356940
 20         1        0        0        0     0.468236                1.624567
 17         0        0        1        0     0.182726               -0.654143
 512        0        0        0        1     1.039256               -1.574681
 191        1        0        0        0    -0.673803               -0.654143
 159        0        0        0        1    -0.959313                1.036026
 286        0        0        0        1     0.753746                1.036026
 561        1        0        0        0     1.610276                2.092381
 134        0        0        0        1    -1.530333               -1.574681
 441        0        0        0        1    -0.102784               -1.574681
 83         0        0        1        0     1.324766               -0.654143
 94         0        0        0        1     1.324766                0.387122
 30         0        0        1        0     0.468236               -0.654143
 110        0        0        0        1     1.610276               -1.574681
 417        0        0        0        1    -0.673803                1.624567
 106        0        0        0        1     1.610276                0.040034
 348        0        0        0        1     1.610276               -0.654143
 226        0        0        0        1    -0.102784               -1.016322
 242        0        0        0        1     0.182726               -1.016322
 260        0        0        0        1     0.468236                0.387122
 639        0        0        0        1    -0.959313                1.005844
 122        0        0        0        1    -1.530333                0.040034
 161        1        0        0        0    -0.959313               -0.654143
 676        0        0        0        1    -0.388293                0.190942
 280        0        0        0        1     0.753746               -0.654143
 410        0        0        1        0    -0.959313                0.568211
 152        0        0        0        1    -1.244823                1.624567
 553        0        0        0        1     1.324766                2.213108
 190        0        0        0        1    -0.673803                0.568211
 658        1        0        0        0    -0.673803               -0.503235

           Age  Body Mass Index  Education  Children      Pets
 427 -0.849811        -0.408580          0  1.780219 -0.589690
 695  0.562059        -1.114186          1  0.880469 -0.589690
 305  1.032682         2.649049          0 -0.019280 -0.589690
 510  1.973929         2.178644          0 -0.919030  1.126663
 650  0.248310         1.002633          0 -0.919030 -0.589690
 613  1.660180         1.237836          0  0.880469  0.268487
 439  0.091435         0.532229          1 -0.019280  0.268487
 454  2.130803         1.002633          0 -0.019280 -0.589690
 677  0.091435         0.297027          0 -0.919030 -0.589690
 141 -0.536062        -0.408580          0  0.880469  1.126663
 188 -0.379188        -0.408580          0  0.880469 -0.589690
 172  0.405184        -0.643782          0  0.880469 -0.589690
 136 -0.536062         0.767431          0  0.880469  0.268487
 176 -1.006686        -1.819793          1 -0.919030 -0.589690
 59   1.660180         1.237836          0  0.880469  0.268487
 318  1.660180         1.237836          0  0.880469  0.268487
 353  0.091435         0.532229          1 -0.019280  0.268487
 311 -0.065439        -0.878984          0  2.679969 -0.589690
 590  0.248310         1.002633          0 -0.919030 -0.589690
 114  0.091435         0.297027          0 -0.919030 -0.589690
 178 -1.320435        -0.643782          0 -0.019280  1.126663
 588  0.248310         1.002633          0 -0.919030 -0.589690
 548  0.562059        -0.408580          0 -0.019280  0.268487
 167 -0.379188        -0.408580          0  0.880469 -0.589690
 290  0.091435         0.532229          1 -0.019280  0.268487
 552 -1.320435        -0.643782          0 -0.019280  1.126663
 670 -0.379188        -0.408580          0  0.880469 -0.589690
 102 -1.320435        -0.643782          0 -0.019280  1.126663
 446  0.248310         1.002633          0 -0.919030 -0.589690
 451  1.032682         2.649049          0 -0.019280 -0.589690
 ..        ...              ...        ...       ...       ...
 457  0.718933        -0.878984          0 -0.919030 -0.589690
 20  -1.320435        -0.408580          1 -0.919030 -0.589690
 17   0.248310         1.002633          0 -0.919030 -0.589690
 512  0.091435         0.297027          0 -0.919030 -0.589690
 191  0.248310         1.002633          0 -0.919030 -0.589690
 159  0.562059        -0.408580          0 -0.019280  0.268487
 286  0.562059        -0.408580          0 -0.019280  0.268487
 561 -1.320435         0.061825          0 -0.019280  2.843016
 134  0.091435         0.297027          0 -0.919030 -0.589690
 441  0.091435         0.297027          0 -0.919030 -0.589690
 83   0.562059        -1.114186          1  0.880469 -0.589690
 94   1.660180         1.237836          0  0.880469  0.268487
 30   0.248310         1.002633          0 -0.919030 -0.589690
 110  0.091435         0.297027          0 -0.919030 -0.589690
 417 -1.320435        -0.408580          1 -0.919030 -0.589690
 106 -1.320435        -0.643782          0 -0.019280  1.126663
 348 -1.006686        -1.819793          1 -0.919030 -0.589690
 226 -0.379188        -0.408580          0  0.880469 -0.589690
 242 -0.379188        -0.408580          0  0.880469 -0.589690
 260  1.660180         1.237836          0  0.880469  0.268487
 639 -0.536062         0.767431          0  0.880469  0.268487
 122 -1.320435        -0.643782          0 -0.019280  1.126663
 161 -1.006686        -1.819793          1 -0.919030 -0.589690
 676 -0.692937        -0.408580          1 -0.919030 -0.589690
 280  0.248310         1.002633          0 -0.919030 -0.589690
 410 -0.065439        -0.878984          0  2.679969 -0.589690
 152 -1.320435        -0.408580          1 -0.919030 -0.589690
 553 -0.849811        -0.408580          0  1.780219 -0.589690
 190 -0.065439        -0.878984          0  2.679969 -0.589690
 658 -0.536062        -0.408580          0  0.880469  1.126663

 [175 rows x 11 columns],
 array([0, 0, 0, 1, 1, 0, 0, 1, 0, 1, 0, 0, 1, 1, 1, 0, 1, 1, 1, 1, 0, 1,
        0, 0, 0, 1, 0, 1, 0, 1, 1, 1, 1, 0, 1, 0, 1, 0, 0, 1, 1, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 1, 1, 0, 0, 0, 1, 0, 0, 0, 1, 0, 0, 1, 1, 0, 0,
        0, 1, 1, 0, 0, 1, 1, 0, 0, 0, 0, 0, 1, 0, 1, 1, 0, 1, 1, 1, 1, 1,
        0, 0, 0, 1, 1, 0, 1, 1, 1, 1, 1, 1, 0, 1, 1, 0, 0, 1, 1, 0, 1, 1,
        0, 0, 0, 1, 1, 1, 0, 0, 0, 0, 0, 0, 0, 1, 0, 1, 1, 1, 0, 1, 1, 1,
        0, 1, 0, 1, 1, 0, 1, 0, 1, 1, 0, 0, 1, 1, 1, 0, 1, 0, 1, 1, 1, 1,
        0, 1, 0, 0, 0, 0, 0, 1, 1, 1, 1, 1, 0, 0, 1, 1, 1, 0, 1, 1, 1, 1,
        0, 0, 0, 1, 1, 0, 0, 0, 0, 0, 0, 0, 1, 0, 1, 1, 1, 0, 1, 1, 0, 0,
        0, 0, 0, 0, 1, 1, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 1, 1, 1,
        0, 0, 0, 0, 1, 1, 0, 1, 0, 0, 1, 0, 0, 0, 0, 1, 0, 1, 0, 1, 0, 0,
        0, 0, 1, 0, 0, 0, 1, 0, 0, 0, 1, 1, 0, 0, 0, 1, 0, 1, 1, 0, 1, 1,
        0, 1, 1, 0, 0, 1, 1, 0, 1, 1, 0, 1, 0, 1, 0, 1, 0, 0, 0, 1, 1, 1,
        0, 1, 1, 0, 1, 1, 0, 0, 0, 1, 0, 0, 1, 1, 0, 0, 0, 0, 0, 0, 1, 0,
        1, 0, 0, 1, 0, 1, 0, 0, 0, 1, 0, 1, 0, 0, 1, 0, 0, 1, 1, 1, 0, 0,
        1, 0, 1, 1, 1, 1, 1, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 1, 0, 0, 0, 0,
        0, 1, 1, 1, 1, 1, 1, 0, 1, 0, 1, 0, 1, 1, 0, 1, 0, 0, 1, 0, 0, 1,
        1, 0, 1, 0, 0, 0, 0, 1, 0, 0, 1, 1, 0, 1, 1, 0, 0, 1, 1, 0, 0, 0,
        1, 0, 0, 1, 0, 0, 0, 0, 1, 0, 1, 0, 1, 0, 0, 1, 1, 1, 1, 1, 0, 0,
        0, 1, 1, 1, 0, 1, 1, 0, 0, 1, 0, 0, 1, 0, 0, 0, 1, 0, 0, 0, 1, 0,
        0, 1, 1, 0, 1, 1, 1, 1, 1, 1, 0, 0, 1, 1, 1, 0, 0, 0, 1, 0, 0, 0,
        0, 0, 1, 1, 1, 0, 0, 1, 0, 1, 0, 0, 1, 1, 0, 1, 1, 1, 1, 0, 1, 0,
        0, 0, 1, 1, 0, 1, 0, 0, 0, 1, 1, 1, 0, 0, 0, 0, 0, 1, 1, 1, 0, 0,
        0, 1, 1, 0, 0, 1, 1, 1, 1, 0, 1, 0, 0, 0, 0, 0, 1, 1, 1]),
 array([1, 1, 0, 0, 0, 0, 1, 0, 0, 1, 0, 1, 0, 0, 0, 0, 1, 0, 0, 0, 1, 0,
        0, 1, 1, 0, 1, 0, 0, 1, 1, 1, 0, 1, 1, 1, 0, 1, 0, 1, 1, 1, 1, 1,
        0, 0, 0, 1, 0, 0, 0, 0, 1, 1, 0, 0, 0, 0, 0, 0, 1, 0, 1, 0, 0, 0,
        1, 1, 0, 0, 0, 0, 0, 0, 1, 0, 0, 1, 0, 1, 1, 0, 1, 1, 0, 1, 1, 0,
        1, 1, 0, 0, 1, 1, 1, 0, 0, 0, 0, 1, 0, 1, 1, 1, 0, 0, 0, 0, 1, 0,
        0, 0, 0, 0, 1, 0, 1, 1, 0, 0, 0, 0, 0, 0, 1, 1, 0, 1, 1, 0, 0, 1,
        0, 1, 1, 1, 0, 1, 0, 0, 1, 0, 1, 1, 0, 0, 1, 1, 0, 1, 1, 0, 1, 0,
        0, 1, 0, 1, 0, 1, 0, 0, 1, 0, 0, 1, 0, 1, 0, 0, 1, 0, 1, 1, 1])]

In [23]:
x_train, x_test, y_train, y_test = train_test_split(scaled_data, targets, train_size=0.8,
                                                    shuffle = 'true',  #shuffle tru by default
                                                    random_state = 7)  #shuffle but not randomized everytime we run the code

In [24]:
print(x_train.shape, y_train.shape)

(560, 11) (560,)

In [25]:
from sklearn.linear_model import LogisticRegression
from sklearn import metrics

In [26]:
reg = LogisticRegression()

In [27]:
reg.fit(x_train, y_train)

E:\Anaconda\Python\lib\site-packages\sklearn\linear_model\logistic.py:432: FutureWarning: Default solver will be changed to 'lbfgs' in 0.22. Specify a solver to silence this warning.
  FutureWarning)

LogisticRegression(C=1.0, class_weight=None, dual=False, fit_intercept=True,
                   intercept_scaling=1, l1_ratio=None, max_iter=100,
                   multi_class='warn', n_jobs=None, penalty='l2',
                   random_state=None, solver='warn', tol=0.0001, verbose=0,
                   warm_start=False)

In [28]:
reg.score(x_train, y_train)

0.7785714285714286

In [29]:
#80% accuracy

In [30]:
#manually check accuracy i.e. build score function

In [31]:
model_outputs = reg.predict(x_train)
model_outputs

array([1, 0, 0, 1, 0, 1, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 1, 1, 0, 1,
       1, 0, 1, 1, 1, 0, 1, 0, 0, 0, 1, 0, 1, 0, 1, 1, 1, 1, 0, 1, 0, 0,
       1, 1, 1, 0, 0, 0, 0, 1, 1, 1, 0, 0, 1, 0, 0, 0, 1, 1, 1, 0, 0, 0,
       1, 0, 1, 0, 0, 1, 1, 0, 1, 1, 1, 0, 0, 1, 0, 0, 0, 0, 0, 0, 1, 1,
       1, 1, 1, 0, 0, 0, 0, 0, 0, 1, 0, 1, 0, 1, 0, 0, 1, 0, 1, 0, 0, 1,
       0, 0, 0, 0, 0, 0, 0, 1, 1, 0, 0, 0, 1, 0, 0, 1, 0, 0, 0, 1, 0, 1,
       1, 0, 1, 1, 0, 1, 0, 0, 1, 1, 0, 1, 0, 1, 0, 1, 1, 1, 0, 1, 1, 0,
       0, 0, 1, 0, 0, 0, 0, 1, 1, 0, 0, 1, 1, 1, 0, 1, 0, 1, 1, 1, 0, 0,
       1, 1, 1, 0, 0, 0, 1, 1, 1, 1, 0, 0, 1, 1, 0, 0, 0, 1, 0, 0, 0, 0,
       0, 1, 1, 1, 0, 1, 0, 1, 0, 1, 0, 0, 1, 1, 0, 1, 0, 1, 0, 1, 0, 0,
       0, 0, 1, 1, 1, 1, 0, 1, 1, 0, 0, 1, 0, 1, 1, 0, 1, 1, 0, 0, 0, 1,
       0, 0, 1, 1, 1, 0, 0, 0, 1, 0, 0, 0, 0, 1, 1, 1, 0, 0, 1, 0, 1, 1,
       0, 1, 1, 1, 0, 1, 1, 0, 1, 1, 1, 1, 0, 0, 1, 1, 1, 1, 1, 1, 1, 0,
       1, 0, 0, 0, 1, 0, 1, 0, 1, 1, 0, 0, 0, 1, 1, 0, 1, 0, 0, 0, 1, 0,
       0, 0, 0, 1, 1, 1, 0, 0, 1, 1, 0, 1, 0, 0, 0, 0, 1, 1, 1, 1, 0, 0,
       0, 1, 1, 0, 0, 0, 0, 1, 0, 0, 0, 0, 1, 0, 0, 1, 0, 0, 0, 0, 1, 1,
       0, 0, 1, 0, 0, 1, 0, 0, 0, 1, 0, 0, 1, 0, 0, 0, 1, 1, 0, 0, 0, 0,
       0, 1, 0, 1, 1, 1, 0, 1, 1, 1, 1, 1, 1, 0, 1, 1, 1, 1, 0, 1, 1, 1,
       0, 0, 0, 1, 1, 0, 0, 1, 0, 0, 0, 1, 1, 0, 1, 1, 0, 0, 1, 0, 1, 0,
       0, 0, 0, 0, 0, 0, 0, 1, 1, 0, 1, 1, 0, 1, 0, 1, 1, 1, 1, 0, 1, 1,
       1, 1, 0, 0, 1, 1, 0, 1, 0, 1, 0, 0, 0, 0, 0, 0, 0, 1, 1, 1, 0, 1,
       1, 0, 1, 0, 1, 1, 0, 0, 1, 0, 1, 1, 0, 1, 0, 0, 1, 0, 0, 0, 0, 1,
       1, 1, 1, 1, 0, 0, 0, 1, 0, 1, 1, 1, 0, 0, 1, 1, 0, 0, 0, 1, 0, 0,
       1, 1, 1, 1, 1, 0, 0, 1, 0, 0, 0, 0, 1, 1, 0, 0, 0, 0, 1, 1, 1, 1,
       0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 1, 1, 0, 1, 1, 0, 1, 0, 0, 1, 0, 0,
       0, 0, 0, 0, 1, 1, 0, 1, 0, 1])

In [32]:
y_train

array([1, 0, 0, 1, 0, 1, 0, 0, 0, 0, 0, 1, 1, 0, 0, 1, 0, 0, 1, 0, 1, 1,
       1, 1, 0, 1, 1, 0, 1, 0, 0, 0, 1, 0, 0, 0, 1, 1, 1, 1, 0, 1, 1, 0,
       0, 1, 1, 0, 1, 0, 0, 1, 1, 1, 0, 0, 1, 0, 0, 0, 0, 1, 0, 0, 0, 0,
       1, 0, 1, 0, 0, 0, 1, 0, 1, 0, 1, 0, 0, 1, 0, 0, 0, 0, 0, 1, 0, 1,
       1, 1, 1, 0, 1, 0, 0, 1, 0, 0, 1, 1, 1, 1, 0, 1, 0, 0, 1, 1, 1, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 1, 0, 0, 1, 0, 0, 1, 1, 0, 1,
       0, 0, 1, 1, 0, 0, 0, 1, 1, 1, 0, 1, 1, 1, 0, 1, 1, 1, 0, 1, 1, 1,
       0, 0, 1, 0, 0, 0, 0, 0, 0, 1, 0, 1, 1, 1, 1, 1, 0, 1, 1, 1, 0, 0,
       1, 1, 1, 0, 0, 0, 0, 1, 0, 1, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 1, 0,
       1, 1, 0, 1, 0, 1, 1, 1, 0, 1, 1, 0, 1, 0, 0, 1, 0, 1, 0, 0, 1, 0,
       1, 0, 1, 0, 1, 1, 0, 1, 1, 0, 1, 1, 0, 1, 1, 0, 1, 1, 0, 0, 1, 1,
       0, 0, 1, 1, 1, 0, 1, 0, 0, 0, 1, 0, 0, 1, 1, 1, 0, 0, 0, 0, 1, 0,
       0, 1, 1, 1, 0, 1, 1, 0, 0, 1, 1, 1, 0, 0, 1, 1, 1, 1, 1, 0, 1, 0,
       1, 0, 0, 0, 1, 0, 1, 0, 1, 1, 0, 0, 0, 1, 1, 0, 1, 1, 0, 0, 1, 0,
       0, 1, 0, 1, 0, 0, 0, 0, 0, 1, 0, 1, 0, 0, 0, 1, 1, 1, 0, 1, 0, 0,
       0, 1, 1, 0, 0, 0, 0, 1, 1, 0, 0, 0, 1, 1, 1, 1, 0, 0, 0, 0, 1, 1,
       0, 0, 1, 0, 0, 0, 0, 1, 0, 1, 0, 1, 1, 1, 0, 0, 1, 1, 1, 1, 1, 0,
       1, 0, 1, 0, 1, 1, 0, 1, 1, 1, 0, 1, 0, 0, 0, 1, 0, 1, 0, 1, 1, 1,
       0, 0, 0, 1, 1, 1, 1, 1, 0, 1, 0, 1, 1, 0, 1, 1, 0, 0, 1, 0, 1, 0,
       0, 0, 1, 1, 0, 0, 0, 1, 1, 0, 1, 1, 0, 1, 0, 0, 1, 1, 1, 0, 1, 1,
       0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 0, 0, 0, 0, 1, 1, 1, 1, 0, 1,
       1, 0, 1, 0, 0, 0, 0, 0, 0, 0, 1, 1, 0, 1, 0, 1, 0, 0, 0, 0, 0, 1,
       1, 0, 1, 0, 1, 0, 0, 0, 0, 1, 1, 1, 0, 0, 1, 1, 0, 0, 1, 1, 0, 0,
       1, 0, 1, 1, 1, 1, 0, 1, 0, 0, 1, 0, 0, 0, 1, 0, 1, 0, 0, 1, 1, 1,
       0, 1, 0, 0, 0, 0, 0, 0, 1, 1, 1, 1, 0, 1, 0, 0, 1, 0, 1, 1, 0, 0,
       1, 0, 0, 0, 0, 1, 1, 1, 1, 1])

In [33]:
model_outputs == y_train

array([ True,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True,  True, False,  True,  True, False,  True,  True,
        True, False, False,  True,  True, False, False,  True,  True,
        True,  True,  True,  True,  True,  True,  True, False,  True,
        True,  True,  True,  True,  True,  True, False,  True, False,
        True,  True,  True, False,  True,  True,  True,  True,  True,
        True,  True,  True,  True,  True,  True, False,  True, False,
        True,  True,  True,  True,  True,  True,  True,  True, False,
        True,  True,  True, False,  True,  True,  True,  True,  True,
        True,  True,  True,  True, False, False,  True,  True,  True,
        True,  True, False,  True,  True, False,  True, False, False,
        True, False,  True,  True, False, False,  True,  True, False,
       False, False,  True,  True,  True,  True,  True,  True,  True,
       False,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True, False,  True,  True,  True, False,  True,  True,
        True,  True, False,  True, False,  True,  True,  True,  True,
       False,  True,  True,  True,  True,  True,  True,  True,  True,
       False,  True,  True,  True,  True,  True,  True,  True, False,
       False, False,  True,  True,  True,  True, False,  True,  True,
        True,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True, False,  True, False,  True,  True,  True, False,
        True,  True,  True,  True, False,  True,  True, False,  True,
       False,  True, False,  True,  True,  True, False,  True,  True,
        True, False,  True,  True, False,  True,  True,  True,  True,
        True, False, False,  True, False,  True,  True, False,  True,
        True,  True,  True,  True,  True, False,  True,  True,  True,
        True,  True,  True,  True,  True,  True, False,  True,  True,
        True,  True,  True,  True,  True, False,  True, False,  True,
       False,  True,  True,  True,  True,  True,  True,  True, False,
        True,  True, False,  True,  True,  True,  True,  True,  True,
        True,  True, False,  True,  True,  True,  True,  True,  True,
        True,  True,  True,  True, False,  True,  True,  True,  True,
        True,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True,  True,  True,  True,  True, False,  True,  True,
        True,  True,  True, False,  True,  True, False, False,  True,
        True, False,  True,  True,  True,  True,  True,  True, False,
        True,  True, False,  True,  True,  True,  True,  True,  True,
        True,  True,  True,  True,  True, False,  True,  True,  True,
        True, False, False,  True,  True,  True,  True,  True,  True,
        True,  True,  True,  True,  True,  True, False,  True, False,
        True,  True,  True, False,  True, False,  True,  True,  True,
        True, False, False, False,  True, False, False, False, False,
        True,  True,  True,  True,  True,  True, False,  True, False,
        True, False,  True, False,  True,  True,  True,  True,  True,
        True,  True,  True,  True,  True, False, False,  True,  True,
       False,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True,  True,  True,  True,  True, False, False,  True,
        True,  True,  True,  True,  True,  True,  True,  True,  True,
        True, False,  True,  True,  True,  True,  True,  True, False,
        True,  True, False, False,  True,  True,  True,  True,  True,
        True, False,  True,  True,  True,  True, False,  True,  True,
        True,  True,  True,  True,  True,  True,  True, False, False,
        True,  True, False,  True,  True,  True,  True,  True,  True,
       False, False,  True,  True,  True,  True,  True,  True, False,
        True, False, False,  True,  True, False,  True,  True,  True,
        True,  True,  True,  True,  True,  True,  True, False,  True,
        True,  True,  True, False,  True,  True,  True, False,  True,
        True,  True,  True, False,  True, False, False, False,  True,
       False,  True, False,  True,  True,  True,  True, False,  True,
        True,  True, False,  True,  True, False, False,  True,  True,
        True,  True, False,  True,  True,  True, False,  True,  True,
        True, False,  True,  True,  True, False,  True, False,  True,
       False,  True])

In [34]:
np.sum((model_outputs == y_train))
#as true = 1 & false = 0

436

In [35]:
np.sum((model_outputs == y_train)) / model_outputs.shape[0]

0.7785714285714286

In [36]:
#To calculate Weights(coeffecients) and Biases(intercepts)

In [37]:
reg.intercept_

array([-1.5399373])

In [38]:
reg.coef_

array([[ 2.82174901,  0.50912413,  2.95869659,  0.73767369,  0.06334092,
         0.60851046, -0.18245548,  0.32113222,  0.08703281,  0.40225936,
        -0.30816547]])

In [39]:
 unscaled_data.columns.values

array(['reason1', 'reason2', 'reason3', 'reason4', 'Month Value',
       'Transportation Expense', 'Age', 'Body Mass Index', 'Education',
       'Children', 'Pets'], dtype=object)

In [40]:
feature_name = unscaled_data.columns.values

In [41]:
summary_table = pd.DataFrame(columns=['Feature Names'], data = feature_name)

summary_table['Coeffecients'] = np.transpose(reg.coef_)

In [42]:
summary_table

             Feature Names  Coeffecients
0                  reason1      2.821749
1                  reason2      0.509124
2                  reason3      2.958697
3                  reason4      0.737674
4              Month Value      0.063341
5   Transportation Expense      0.608510
6                      Age     -0.182455
7          Body Mass Index      0.321132
8                Education      0.087033
9                 Children      0.402259
10                    Pets     -0.308165

In [43]:
summary_table.index = summary_table.index + 1
summary_table.loc[0] = ['Intercept', reg.intercept_[0]]
summary_table = summary_table.sort_index()
summary_table

             Feature Names  Coeffecients
0                Intercept     -1.539937
1                  reason1      2.821749
2                  reason2      0.509124
3                  reason3      2.958697
4                  reason4      0.737674
5              Month Value      0.063341
6   Transportation Expense      0.608510
7                      Age     -0.182455
8          Body Mass Index      0.321132
9                Education      0.087033
10                Children      0.402259
11                    Pets     -0.308165

In [44]:
summary_table['Odds Ratio'] = np.exp(summary_table.Coeffecients)
summary_table

             Feature Names  Coeffecients  Odds Ratio
0                Intercept     -1.539937    0.214395
1                  reason1      2.821749   16.806219
2                  reason2      0.509124    1.663833
3                  reason3      2.958697   19.272835
4                  reason4      0.737674    2.091065
5              Month Value      0.063341    1.065390
6   Transportation Expense      0.608510    1.837692
7                      Age     -0.182455    0.833222
8          Body Mass Index      0.321132    1.378688
9                Education      0.087033    1.090932
10                Children      0.402259    1.495199
11                    Pets     -0.308165    0.734794

In [45]:
summary_table.sort_values('Odds Ratio', ascending = False)

             Feature Names  Coeffecients  Odds Ratio
3                  reason3      2.958697   19.272835
1                  reason1      2.821749   16.806219
4                  reason4      0.737674    2.091065
6   Transportation Expense      0.608510    1.837692
2                  reason2      0.509124    1.663833
10                Children      0.402259    1.495199
8          Body Mass Index      0.321132    1.378688
9                Education      0.087033    1.090932
5              Month Value      0.063341    1.065390
7                      Age     -0.182455    0.833222
11                    Pets     -0.308165    0.734794
0                Intercept     -1.539937    0.214395

In [ ]:
#Testing

In [46]:
reg.score(x_test,y_test)

0.7428571428571429

In [ ]:
#in 74.2% of cases, model will predict correctly if a person is going to be excessively absent

In [47]:
predicted_proba = reg.predict_proba(x_test)
predicted_proba

array([[0.76682306, 0.23317694],
       [0.87725305, 0.12274695],
       [0.45719054, 0.54280946],
       [0.30602789, 0.69397211],
       [0.21657019, 0.78342981],
       [0.7434289 , 0.2565711 ],
       [0.75123055, 0.24876945],
       [0.63990045, 0.36009955],
       [0.63175696, 0.36824304],
       [0.17508283, 0.82491717],
       [0.7434289 , 0.2565711 ],
       [0.87725305, 0.12274695],
       [0.76682306, 0.23317694],
       [0.26346408, 0.73653592],
       [0.73607722, 0.26392278],
       [0.85801515, 0.14198485],
       [0.35049938, 0.64950062],
       [0.36509373, 0.63490627],
       [0.76357387, 0.23642613],
       [0.13911568, 0.86088432],
       [0.77682091, 0.22317909],
       [0.45719054, 0.54280946],
       [0.62801903, 0.37198097],
       [0.7434289 , 0.2565711 ],
       [0.05626444, 0.94373556],
       [0.62730645, 0.37269355],
       [0.76029356, 0.23970644],
       [0.83777046, 0.16222954],
       [0.27209107, 0.72790893],
       [0.62330326, 0.37669674],
       [0.62306879, 0.37693121],
       [0.2277329 , 0.7722671 ],
       [0.72899103, 0.27100897],
       [0.12156569, 0.87843431],
       [0.06549193, 0.93450807],
       [0.38858087, 0.61141913],
       [0.63152465, 0.36847535],
       [0.40417718, 0.59582282],
       [0.4259855 , 0.5740145 ],
       [0.17047031, 0.82952969],
       [0.16452234, 0.83547766],
       [0.23266487, 0.76733513],
       [0.75363996, 0.24636004],
       [0.76357387, 0.23642613],
       [0.37983382, 0.62016618],
       [0.56498557, 0.43501443],
       [0.83026106, 0.16973894],
       [0.7434289 , 0.2565711 ],
       [0.46414697, 0.53585303],
       [0.87725305, 0.12274695],
       [0.55681987, 0.44318013],
       [0.38839003, 0.61160997],
       [0.21665229, 0.78334771],
       [0.76682306, 0.23317694],
       [0.83700919, 0.16299081],
       [0.81983615, 0.18016385],
       [0.86295809, 0.13704191],
       [0.34639367, 0.65360633],
       [0.76682306, 0.23317694],
       [0.76357387, 0.23642613],
       [0.7645023 , 0.2354977 ],
       [0.72899103, 0.27100897],
       [0.85801515, 0.14198485],
       [0.64475567, 0.35524433],
       [0.27568756, 0.72431244],
       [0.91800726, 0.08199274],
       [0.57999757, 0.42000243],
       [0.76682306, 0.23317694],
       [0.84262637, 0.15737363],
       [0.72899103, 0.27100897],
       [0.40853968, 0.59146032],
       [0.09341389, 0.90658611],
       [0.91093882, 0.08906118],
       [0.18151836, 0.81848164],
       [0.71814043, 0.28185957],
       [0.85127649, 0.14872351],
       [0.5395767 , 0.4604233 ],
       [0.27931335, 0.72068665],
       [0.25898952, 0.74101048],
       [0.85355156, 0.14644844],
       [0.62730645, 0.37269355],
       [0.84188359, 0.15811641],
       [0.53365647, 0.46634353],
       [0.7645023 , 0.2354977 ],
       [0.58767163, 0.41232837],
       [0.06331278, 0.93668722],
       [0.76951384, 0.23048616],
       [0.76682306, 0.23317694],
       [0.85579771, 0.14420229],
       [0.20161967, 0.79838033],
       [0.86508278, 0.13491722],
       [0.51253034, 0.48746966],
       [0.16849071, 0.83150929],
       [0.76682306, 0.23317694],
       [0.76075314, 0.23924686],
       [0.06291908, 0.93708092],
       [0.50380493, 0.49619507],
       [0.36713976, 0.63286024],
       [0.74686316, 0.25313684],
       [0.42918578, 0.57081422],
       [0.20162175, 0.79837825],
       [0.76357387, 0.23642613],
       [0.76357387, 0.23642613],
       [0.76774261, 0.23225739],
       [0.27259114, 0.72740886],
       [0.28665184, 0.71334816],
       [0.42476114, 0.57523886],
       [0.45068285, 0.54931715],
       [0.19696882, 0.80303118],
       [0.84897234, 0.15102766],
       [0.73607722, 0.26392278],
       [0.86080533, 0.13919467],
       [0.48669405, 0.51330595],
       [0.83700919, 0.16299081],
       [0.39549808, 0.60450192],
       [0.11314059, 0.88685941],
       [0.68965956, 0.31034044],
       [0.12329339, 0.87670661],
       [0.53815424, 0.46184576],
       [0.8251028 , 0.1748972 ],
       [0.63572283, 0.36427717],
       [0.76682306, 0.23317694],
       [0.26498688, 0.73501312],
       [0.52915322, 0.47084678],
       [0.52464522, 0.47535478],
       [0.07952577, 0.92047423],
       [0.85417658, 0.14582342],
       [0.54854845, 0.45145155],
       [0.30602789, 0.69397211],
       [0.75698222, 0.24301778],
       [0.7645023 , 0.2354977 ],
       [0.75363996, 0.24636004],
       [0.6934674 , 0.3065326 ],
       [0.74442231, 0.25557769],
       [0.92068885, 0.07931115],
       [0.56572605, 0.43427395],
       [0.84897234, 0.15102766],
       [0.85641477, 0.14358523],
       [0.7434289 , 0.2565711 ],
       [0.61096966, 0.38903034]])

In [48]:
#all probabilities of being 1
predicted_proba[:,1]

array([0.23317694, 0.12274695, 0.54280946, 0.69397211, 0.78342981,
       0.2565711 , 0.24876945, 0.36009955, 0.36824304, 0.82491717,
       0.2565711 , 0.12274695, 0.23317694, 0.73653592, 0.26392278,
       0.14198485, 0.64950062, 0.63490627, 0.23642613, 0.86088432,
       0.22317909, 0.54280946, 0.37198097, 0.2565711 , 0.94373556,
       0.37269355, 0.23970644, 0.16222954, 0.72790893, 0.37669674,
       0.37693121, 0.7722671 , 0.27100897, 0.87843431, 0.93450807,
       0.61141913, 0.36847535, 0.59582282, 0.5740145 , 0.82952969,
       0.83547766, 0.76733513, 0.24636004, 0.23642613, 0.62016618,
       0.43501443, 0.16973894, 0.2565711 , 0.53585303, 0.12274695,
       0.44318013, 0.61160997, 0.78334771, 0.23317694, 0.16299081,
       0.18016385, 0.13704191, 0.65360633, 0.23317694, 0.23642613,
       0.2354977 , 0.27100897, 0.14198485, 0.35524433, 0.72431244,
       0.08199274, 0.42000243, 0.23317694, 0.15737363, 0.27100897,
       0.59146032, 0.90658611, 0.08906118, 0.81848164, 0.28185957,
       0.14872351, 0.4604233 , 0.72068665, 0.74101048, 0.14644844,
       0.37269355, 0.15811641, 0.46634353, 0.2354977 , 0.41232837,
       0.93668722, 0.23048616, 0.23317694, 0.14420229, 0.79838033,
       0.13491722, 0.48746966, 0.83150929, 0.23317694, 0.23924686,
       0.93708092, 0.49619507, 0.63286024, 0.25313684, 0.57081422,
       0.79837825, 0.23642613, 0.23642613, 0.23225739, 0.72740886,
       0.71334816, 0.57523886, 0.54931715, 0.80303118, 0.15102766,
       0.26392278, 0.13919467, 0.51330595, 0.16299081, 0.60450192,
       0.88685941, 0.31034044, 0.87670661, 0.46184576, 0.1748972 ,
       0.36427717, 0.23317694, 0.73501312, 0.47084678, 0.47535478,
       0.92047423, 0.14582342, 0.45145155, 0.69397211, 0.24301778,
       0.2354977 , 0.24636004, 0.3065326 , 0.25557769, 0.07931115,
       0.43427395, 0.15102766, 0.14358523, 0.2565711 , 0.38903034])

In [50]:
import pickle

In [51]:
with open('Absentee_model','wb') as file:
    pickle.dump(reg,file)

In [52]:
with open('Absentee_scaler','wb') as file:
    pickle.dump(absenteeism_scaler,file)